// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcsample/grpc-sample.proto

package grpc_sample

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestType) Reset()         { *m = RequestType{} }
func (m *RequestType) String() string { return proto.CompactTextString(m) }
func (*RequestType) ProtoMessage()    {}
func (*RequestType) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_sample_8ee11f9f828ceb3f, []int{0}
}
func (m *RequestType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestType.Unmarshal(m, b)
}
func (m *RequestType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestType.Marshal(b, m, deterministic)
}
func (dst *RequestType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestType.Merge(dst, src)
}
func (m *RequestType) XXX_Size() int {
	return xxx_messageInfo_RequestType.Size(m)
}
func (m *RequestType) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestType.DiscardUnknown(m)
}

var xxx_messageInfo_RequestType proto.InternalMessageInfo

type MyFileResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyFileResponse) Reset()         { *m = MyFileResponse{} }
func (m *MyFileResponse) String() string { return proto.CompactTextString(m) }
func (*MyFileResponse) ProtoMessage()    {}
func (*MyFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_sample_8ee11f9f828ceb3f, []int{1}
}
func (m *MyFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyFileResponse.Unmarshal(m, b)
}
func (m *MyFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyFileResponse.Marshal(b, m, deterministic)
}
func (dst *MyFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyFileResponse.Merge(dst, src)
}
func (m *MyFileResponse) XXX_Size() int {
	return xxx_messageInfo_MyFileResponse.Size(m)
}
func (m *MyFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MyFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MyFileResponse proto.InternalMessageInfo

func (m *MyFileResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestType)(nil), "RequestType")
	proto.RegisterType((*MyFileResponse)(nil), "MyFileResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileClient is the client API for File service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileClient interface {
	GetMyFile(ctx context.Context, in *RequestType, opts ...grpc.CallOption) (File_GetMyFileClient, error)
}

type fileClient struct {
	cc *grpc.ClientConn
}

func NewFileClient(cc *grpc.ClientConn) FileClient {
	return &fileClient{cc}
}

func (c *fileClient) GetMyFile(ctx context.Context, in *RequestType, opts ...grpc.CallOption) (File_GetMyFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_File_serviceDesc.Streams[0], "/File/GetMyFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileGetMyFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type File_GetMyFileClient interface {
	Recv() (*MyFileResponse, error)
	grpc.ClientStream
}

type fileGetMyFileClient struct {
	grpc.ClientStream
}

func (x *fileGetMyFileClient) Recv() (*MyFileResponse, error) {
	m := new(MyFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileServer is the server API for File service.
type FileServer interface {
	GetMyFile(*RequestType, File_GetMyFileServer) error
}

func RegisterFileServer(s *grpc.Server, srv FileServer) {
	s.RegisterService(&_File_serviceDesc, srv)
}

func _File_GetMyFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestType)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileServer).GetMyFile(m, &fileGetMyFileServer{stream})
}

type File_GetMyFileServer interface {
	Send(*MyFileResponse) error
	grpc.ServerStream
}

type fileGetMyFileServer struct {
	grpc.ServerStream
}

func (x *fileGetMyFileServer) Send(m *MyFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _File_serviceDesc = grpc.ServiceDesc{
	ServiceName: "File",
	HandlerType: (*FileServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMyFile",
			Handler:       _File_GetMyFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpcsample/grpc-sample.proto",
}

func init() {
	proto.RegisterFile("grpcsample/grpc-sample.proto", fileDescriptor_grpc_sample_8ee11f9f828ceb3f)
}

var fileDescriptor_grpc_sample_8ee11f9f828ceb3f = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x2f, 0x2a, 0x48,
	0x2e, 0x4e, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x07, 0x31, 0x75, 0x21, 0x6c, 0xbd, 0x82, 0xa2, 0xfc,
	0x92, 0x7c, 0x25, 0x5e, 0x2e, 0xee, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x92, 0x90, 0xca, 0x82,
	0x54, 0x25, 0x15, 0x2e, 0x3e, 0xdf, 0x4a, 0xb7, 0xcc, 0x9c, 0xd4, 0xa0, 0xd4, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x30, 0xdb, 0xc8, 0x8c, 0x8b, 0x05, 0xa4, 0x46, 0x48, 0x8f, 0x8b, 0xd3, 0x3d, 0xb5,
	0x04, 0xa2, 0x41, 0x88, 0x47, 0x0f, 0xc9, 0x20, 0x29, 0x7e, 0x3d, 0x54, 0x73, 0x94, 0x18, 0x0c,
	0x18, 0x93, 0xd8, 0xc0, 0x76, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x77, 0x8d, 0x43,
	0x93, 0x00, 0x00, 0x00,
}
